# 09_collector — needs SAI (audio) + LPI2C (PCA9685) + LPSPI (ILI9341).
CONFIG_MCUX_COMPONENT_driver.sai=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpuart=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpi2c=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpspi=y
